;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/LHW/BossData/DT_Tag.DT_Tag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ACTION.Attack",DevComment="")
+GameplayTagList=(Tag="ACTION.Attack.LightAttack",DevComment="")
+GameplayTagList=(Tag="ACTION.Attack.LightAttack.Step1",DevComment="")
+GameplayTagList=(Tag="ACTION.Attack.LightAttack.Step2",DevComment="")
+GameplayTagList=(Tag="ACTION.Attack.LightAttack.Step3",DevComment="")
+GameplayTagList=(Tag="ACTION.Attack.LightAttack.Step4",DevComment="")
+GameplayTagList=(Tag="ACTION.NextAttack",DevComment="")
+GameplayTagList=(Tag="Attack.Combo1-1",DevComment="")

